exports.home = require('./home')
exports.enCartelera = require('./enCartelera')
exports.masVotadas = require('./masVotadas')
exports.sucursales = require('./sucursales')
exports.contacto = require('./contacto')
exports.preguntasFrecuentes = require('./preguntasFrecuentes')
exports.route = require('./route')
